// <auto-generated />
using System;
using FitCorePro.Nutrition.Tracking.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitCorePro.Nutrition.Tracking.Infrastructure.Migrations
{
    [DbContext(typeof(TrackingDbContext))]
    [Migration("20260422170541_InitialTracking")]
    partial class InitialTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitCorePro.Nutrition.Tracking.Domain.Entities.AlimentoBase", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<double>("Calorias")
                        .HasColumnType("double precision");

                    b.Property<double>("Carboidratos")
                        .HasColumnType("double precision");

                    b.Property<double>("Fibras")
                        .HasColumnType("double precision");

                    b.Property<double>("Gorduras")
                        .HasColumnType("double precision");

                    b.Property<int>("Gramas")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(355)
                        .HasColumnType("character varying(355)");

                    b.Property<double>("Proteinas")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("TB_ALIMENTO_BASE", (string)null);
                });

            modelBuilder.Entity("FitCorePro.Nutrition.Tracking.Domain.Entities.AlimentoDietaDia", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<double>("Calorias")
                        .HasColumnType("double precision");

                    b.Property<double>("Carboidratos")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Fibras")
                        .HasColumnType("double precision");

                    b.Property<double>("Gorduras")
                        .HasColumnType("double precision");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(355)
                        .HasColumnType("character varying(355)");

                    b.Property<double>("Proteinas")
                        .HasColumnType("double precision");

                    b.Property<int>("QuantidadeGramas")
                        .HasColumnType("integer");

                    b.Property<string>("RefeicaoDietaDiaId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.HasKey("Id");

                    b.HasIndex("RefeicaoDietaDiaId");

                    b.ToTable("TB_ALIMENTO_DIETA_DIA", (string)null);
                });

            modelBuilder.Entity("FitCorePro.Nutrition.Tracking.Domain.Entities.DietaDia", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataDieta")
                        .HasColumnType("date");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("TB_DIETA_DIA", (string)null);
                });

            modelBuilder.Entity("FitCorePro.Nutrition.Tracking.Domain.Entities.RefeicaoDietaDia", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DietaDiaId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("DietaDiaId");

                    b.ToTable("TB_REFEICAO_DIETA_DIA", (string)null);
                });

            modelBuilder.Entity("FitCorePro.Nutrition.Tracking.Domain.Entities.AlimentoDietaDia", b =>
                {
                    b.HasOne("FitCorePro.Nutrition.Tracking.Domain.Entities.RefeicaoDietaDia", "RefeicaoDietaDia")
                        .WithMany("AlimentosDietaDia")
                        .HasForeignKey("RefeicaoDietaDiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RefeicaoDietaDia");
                });

            modelBuilder.Entity("FitCorePro.Nutrition.Tracking.Domain.Entities.RefeicaoDietaDia", b =>
                {
                    b.HasOne("FitCorePro.Nutrition.Tracking.Domain.Entities.DietaDia", "DietaDia")
                        .WithMany("RefeicoesDietaDia")
                        .HasForeignKey("DietaDiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietaDia");
                });

            modelBuilder.Entity("FitCorePro.Nutrition.Tracking.Domain.Entities.DietaDia", b =>
                {
                    b.Navigation("RefeicoesDietaDia");
                });

            modelBuilder.Entity("FitCorePro.Nutrition.Tracking.Domain.Entities.RefeicaoDietaDia", b =>
                {
                    b.Navigation("AlimentosDietaDia");
                });
#pragma warning restore 612, 618
        }
    }
}
