// <auto-generated />
using System;
using FitCorePro.Nutrition.Planning.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitCorePro.Nutrition.Planning.Infrastructure.Migrations
{
    [DbContext(typeof(PlanningDbContext))]
    partial class PlanningDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitCorePro.Nutrition.Planning.Domain.Entities.AlimentoPlanoSemanal", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Gramas")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RefeicaoPlanoSemanalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.HasKey("Id");

                    b.HasIndex("RefeicaoPlanoSemanalId");

                    b.ToTable("TB_ALIMENTO_PLANO_SEMANAL", (string)null);
                });

            modelBuilder.Entity("FitCorePro.Nutrition.Planning.Domain.Entities.PlanoSemanal", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(355)
                        .HasColumnType("character varying(355)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("TB_PLANO_SEMANAL", (string)null);
                });

            modelBuilder.Entity("FitCorePro.Nutrition.Planning.Domain.Entities.PlanoSemanalDia", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<string>("PlanoSemanalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.HasKey("Id");

                    b.HasIndex("PlanoSemanalId");

                    b.ToTable("TB_PLANO_SEMANAL_DIA", (string)null);
                });

            modelBuilder.Entity("FitCorePro.Nutrition.Planning.Domain.Entities.RefeicaoPlanoSemanal", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<string>("PlanoSemanalDiaId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("PlanoSemanalDiaId");

                    b.ToTable("TB_REFEICAO_PLANO_SEMANAL", (string)null);
                });

            modelBuilder.Entity("FitCorePro.Nutrition.Planning.Domain.Entities.AlimentoPlanoSemanal", b =>
                {
                    b.HasOne("FitCorePro.Nutrition.Planning.Domain.Entities.RefeicaoPlanoSemanal", "RefeicaoPlanoSemanal")
                        .WithMany("AlimentosPlanoSemanais")
                        .HasForeignKey("RefeicaoPlanoSemanalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RefeicaoPlanoSemanal");
                });

            modelBuilder.Entity("FitCorePro.Nutrition.Planning.Domain.Entities.PlanoSemanalDia", b =>
                {
                    b.HasOne("FitCorePro.Nutrition.Planning.Domain.Entities.PlanoSemanal", "PlanoSemanal")
                        .WithMany("PlanoSemanalDias")
                        .HasForeignKey("PlanoSemanalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanoSemanal");
                });

            modelBuilder.Entity("FitCorePro.Nutrition.Planning.Domain.Entities.RefeicaoPlanoSemanal", b =>
                {
                    b.HasOne("FitCorePro.Nutrition.Planning.Domain.Entities.PlanoSemanalDia", "PlanoSemanalDia")
                        .WithMany("RefeicoesPlanoSemanal")
                        .HasForeignKey("PlanoSemanalDiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanoSemanalDia");
                });

            modelBuilder.Entity("FitCorePro.Nutrition.Planning.Domain.Entities.PlanoSemanal", b =>
                {
                    b.Navigation("PlanoSemanalDias");
                });

            modelBuilder.Entity("FitCorePro.Nutrition.Planning.Domain.Entities.PlanoSemanalDia", b =>
                {
                    b.Navigation("RefeicoesPlanoSemanal");
                });

            modelBuilder.Entity("FitCorePro.Nutrition.Planning.Domain.Entities.RefeicaoPlanoSemanal", b =>
                {
                    b.Navigation("AlimentosPlanoSemanais");
                });
#pragma warning restore 612, 618
        }
    }
}
