// <auto-generated />
using FitCorePro.Training.Planning.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitCorePro.Training.Planning.Infrastructure.Migrations
{
    [DbContext(typeof(TraniningDbContext))]
    partial class TraniningDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitCorePro.Training.Planning.Domain.Entities.Exercicio", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("Carga")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TipoExercicio")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TreinoDiaId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.HasKey("Id");

                    b.HasIndex("TreinoDiaId");

                    b.ToTable("TB_EXERCICIO", (string)null);
                });

            modelBuilder.Entity("FitCorePro.Training.Planning.Domain.Entities.PlanoTreinoSemanal", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.HasKey("Id");

                    b.ToTable("TB_PLANO_TREINO_SEMANAL", (string)null);
                });

            modelBuilder.Entity("FitCorePro.Training.Planning.Domain.Entities.TreinoDia", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<string>("PlanoTreinoSemanalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.HasKey("Id");

                    b.HasIndex("PlanoTreinoSemanalId");

                    b.ToTable("TB_TREINO_DIA", (string)null);
                });

            modelBuilder.Entity("FitCorePro.Training.Planning.Domain.Entities.Exercicio", b =>
                {
                    b.HasOne("FitCorePro.Training.Planning.Domain.Entities.TreinoDia", "TreinoDia")
                        .WithMany("Exercicios")
                        .HasForeignKey("TreinoDiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TreinoDia");
                });

            modelBuilder.Entity("FitCorePro.Training.Planning.Domain.Entities.TreinoDia", b =>
                {
                    b.HasOne("FitCorePro.Training.Planning.Domain.Entities.PlanoTreinoSemanal", "PlanoTreinoSemanal")
                        .WithMany("TreinosDia")
                        .HasForeignKey("PlanoTreinoSemanalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanoTreinoSemanal");
                });

            modelBuilder.Entity("FitCorePro.Training.Planning.Domain.Entities.PlanoTreinoSemanal", b =>
                {
                    b.Navigation("TreinosDia");
                });

            modelBuilder.Entity("FitCorePro.Training.Planning.Domain.Entities.TreinoDia", b =>
                {
                    b.Navigation("Exercicios");
                });
#pragma warning restore 612, 618
        }
    }
}
